config/routes.rb
Rails.application.routes.draw do

  root "sessions#home"
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/auth/facebook/callback' => 'sessions#create_fb'
  delete '/logout' => 'sessions#destroy'
  resources :maintenance_features
  resources :comments
  resources :users
  resources :trails do
    resources :maintenance_features
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :maintenance_feature
end

app/models/maintenance_feature.rb
class MaintenanceFeature < ApplicationRecord
  validates :location, :issue, presence: true
  belongs_to :trail
  belongs_to :user
  has_many :tools
  scope :needs_attention, -> { where(task_completed: false) }
  scope :task_completed, -> { where(task_completed: true) }
  

  def trail_name
    trail.name 
  end
  def attributes_string
    "Location: #{location}, Issue: #{issue}, Tools Needed: #{tools_needed}, Task Status: #{task_status}"
  end

  def task_status
    if task_completed
      "Task Completed"
    else
      "Needs Attention"
    end
  end
  

end

app/models/tool.rb
class Tool < ApplicationRecord
  belongs_to :user
  has_many :maintenance_features
end

app/models/trail.rb
class Trail < ApplicationRecord
  validates :name, :location, presence: true
  validates :name, uniqueness: true
  has_many :maintenance_features
  has_many :users, through: :maintenance_features
end

app/models/user.rb
class User < ApplicationRecord
    validates :email, uniqueness: true
    has_many :maintenance_features
    has_many :tools
    has_many :comments
    has_many :trails, through: :maintenance_features
    has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include ApplicationHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/maintenance_features_controller.rb
class MaintenanceFeaturesController < ApplicationController
include MaintenanceFeaturesHelper
    before_action :redirect_if_not_logged_in
    
    def index
        @maintenance_feature_needs_attention = MaintenanceFeature.needs_attention
        @maintenance_feature_task_completed = MaintenanceFeature.task_completed
    end
    def new
        @trail_id = params[:trail_id]
        @maintenance_feature = MaintenanceFeature.new
    end

    def create
        @maintenance_feature = current_user.maintenance_features.new(maintenance_feature_params)
        if @maintenance_feature.save
            redirect_to trail_path(@maintenance_feature.trail_id)
        else
            maintenance_feature_error_messages
            redirect_to new_trail_maintenance_feature_path(@maintenance_feature.trail_id)
        end
    end
    def show
        current_maintenance_feature
    end

    def edit 
        @trail_id = params[:trail_id]
        @maintenance_feature = MaintenanceFeature.find(params[:id])
       
    end

    def update
    @maintenance_feature = MaintenanceFeature.find_by(id: params[:id])
        @maintenance_feature.update(maintenance_feature_params)
        if @maintenance_feature.valid?
            redirect_to maintenance_feature_path(@maintenance_feature)
        else
            maintenance_feature_error_messages
            render :edit
        end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper
  def home
    current_user
  end

  def new
    @user = User.new
  end

  def create_fb
    if @user = User.find_or_create_by(uid: auth['uid']) do |u|
      u.name = auth['info']['name']
      u.email = auth['info']['email']
      u.image = auth['info']['image']
      u.password = SecureRandom.alphanumeric(10)
      end
      session[:user_id] = @user.id
      render :home
    else
      flash[:alert] = @user.error.full_messages
    end
  end

  def create
    @user = User.find_by(email: params[:user][:email])
    if @user && @user.authenticate(params[:user][:password])
      flash[:message]= "You are sign in"
      session[:user_id] = @user.id
      render :home
    else
      flash[:message] = "Please try to login again"
      redirect_to login_path
    end
  end

  def show
  end

  def update
  end

  def destroy
    session.clear
    redirect_to login_path
  end

  private
  

end

app/controllers/trails_controller.rb
class TrailsController < ApplicationController
    include TrailsHelper
before_action :redirect_if_not_logged_in
    def new
        @trail = Trail.new
    end

    def index
        @trails = Trail.all
    end

    def create
        @trail = Trail.new(trail_params)
        if @trail.save
            redirect_to trail_path(@trail)
        else
            trail_error_messages
            render :new
        end
    end

    def show
        find_trail_by_id
    end
     
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user_id
            redirect_to @user
        else
            render :new
        end
    end

    def show
        current_user

    end

    private

    def user_params
        params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def current_user
        @user ||= User.find_by_id(session[:user_id])
    end

    def logged_in?
        !!current_user
    end

    def logged_out?
        !current_user
    end

    def redirect_if_not_logged_in
        redirect_to login_path if !logged_in?
    
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/maintenance_features_helper.rb
module MaintenanceFeaturesHelper
    
    def maintenance_feature_params
        params.require(:maintenance_feature).permit(:location, :issue, :tools_needed, :trail_id, :task_completed)
    end

    def current_maintenance_feature
        @maintenance_feature = MaintenanceFeature.find(params[:id])
    end

    def maintenance_feature_error_messages
        flash[:message] = @maintenance_feature.errors.full_messages.join(", ")
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def auth
        request.env['omniauth.auth']
      end
end

app/helpers/trails_helper.rb
module TrailsHelper
    
    def trail_params
        params.require(:trail).permit(:name, :location)
    end

    def find_trail_by_id
        @trail = Trail.find_by_id(params[:id])
    end

    def trail_error_messages
        flash[:message] = @trail.errors.full_messages
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-light" style="background-color: #643F2F;">
<ul class="nav">
  <li class="nav-item" style="color: #78c4d4">
    <a class="nav-link active" aria-current="page" href="/">Trail Head</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/trails">Trails</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/maintenance_features">Valet</a>
  </li>
</ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link href="/stylesheets/application.css" rel="stylesheet" type="text/css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>TrailValet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    
  </head>

  <body style="background-color: #43070E;">
  
  <%= render 'layouts/nav' %>
  <% if flash[:message]%>
  <div class="text-warning" style="background-color: #43070E;">
  <%= flash[:message]%><br>
  </div>
  <%end%>
<div class="mx-auto" style="width: 800px; background-color: #AE321D">
  <%= yield %>
</div>
   
    <br>
    <% if logged_in? %>
    <%= button_to 'Log out', logout_url, method: 'delete', :class => 'button' %>
    <% end %>

    <% if logged_out? %>
    <%= link_to(controller: 'sessions', action: 'new') { 'Log in' } %>
    <%= link_to(controller: 'users', action: 'new') { 'sign up' } %>
    <% end %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
  </body>
</html>

app/views/maintenance_features/_form.html.erb
<%= form_for @maintenance_feature do |f| %>
<%= f.label :location %>
<%= f.text_field :location%> <br>

<%= f.label :issue %>
<%= f.text_field :issue %> <br>

<%= f.label :tools_needed %>
<%= f.text_field :tools_needed%> <br>
<%= f.select :task_completed, [["Task Completed", true], ["Needs Attention", false]]%><br>
<%= f.hidden_field :trail_id, value: @trail_id %>
<%= f.submit "#{submit_button}", :class => 'button' %>
<% end%>

app/views/maintenance_features/_maintenance_feature.html.erb
<%= link_to maintenance_feature.trail_name, trail_path(maintenance_feature.trail) %><br>
<%= maintenance_feature.attributes_string %><br>
<%= link_to 'Edit or Delete this issue', edit_trail_maintenance_feature_path(maintenance_feature.trail_id, maintenance_feature) %><br>
<%= link_to "New Maintenance or Feature for #{maintenance_feature.trail_name}", new_trail_maintenance_feature_path(maintenance_feature.trail) %><br>

app/views/maintenance_features/edit.html.erb
<h3>Edit Maintenance or Feature</h3>
<%= render partial: 'form', locals: {submit_button: "Edit Maintenance or Feature"}%>
<%= button_to 'Delete Maintenance or Feature', maintenance_feature_path(@maintenance_feature), method: "delete", :class => 'button' %>

app/views/maintenance_features/index.html.erb
<h3>Needs Valet</h3>
<%=render partial: 'maintenance_feature', collection: @maintenance_feature_needs_attention, as: :maintenance_feature %>
<h3>Valeted Trails</h3>
<%=render partial: 'maintenance_feature', collection: @maintenance_feature_task_completed, as: :maintenance_feature %>

app/views/maintenance_features/new.html.erb
<h3>New Maintenance or Feature</h3>
<%= render partial: 'form', locals: {submit_button: "New Maintenance or Feature"}%>

app/views/maintenance_features/show.html.erb
<%=render partial: 'maintenance_feature', locals: {maintenance_feature: @maintenance_feature}  %>

app/views/trails/_form.html.erb
<%= form_for trail do |f| %>
<%= f.label :name %>
<%= f.text_field :name %><br>

<%= f.label :location %>
<%= f.text_field :location %><br>

<%= f.submit "Create Trail", :class => 'button' %>
<% end %>

app/views/trails/_trail.html.erb
<li>Trail: <%= link_to trail.name, trail_path(trail) %></li>
    Location: <%= trail.location%>
    <ul>
    <% trail.maintenance_features.each do |mf| %>
   <li><%= link_to  "#{mf.attributes_string}", trail_maintenance_feature_path(mf.trail.id, mf) %></li>
    <%end%>
    </ul>
    <%= link_to "Create Maintenance or Feature for #{trail.name}", new_trail_maintenance_feature_path(trail) %>

app/views/trails/index.html.erb
<h3>All Trails</h3>
<ol>
<%= render @trails %>
</ol>
<%= button_to 'Create New Trail', new_trail_path, method: 'get', :class => 'button' %>

app/views/trails/new.html.erb
<h3> Create Trail </h3>
<%=render partial: 'form', locals: {trail: @trail}  %>

app/views/trails/show.html.erb
<%= render partial: 'trail', locals: {trail: @trail} %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user, url: '/signup'  do |f| %>
<%= f.label :name %>
<%= f.text_field :name%>
<br>
<%= f.label :email %>
<%= f.email_field :email%>
<br>
<%= f.label :password %>
<%= f.password_field :password%>

<%= f.submit "Submit" %>
  
<% end %>

app/views/users/show.html.erb
<h1>Welcome <%=@user.name %></h1>
<%= link_to 'Add new trail', new_trail_path %>